# Generated by Django 2.1.5 on 2019-03-08 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(default='', max_length=100, unique=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('plant', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('V', 'Vine'), ('O', 'Overland')], default='N', max_length=4)),
                ('shift', models.IntegerField(default=1)),
                ('department', models.CharField(choices=[('P', 'Production'), ('Q', 'Quality'), ('S', 'Sanitation'), ('W', 'Warehouse'), ('A', 'Admin')], default='P', max_length=4)),
                ('title', models.CharField(default='', max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StepReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('step', models.CharField(default='0', max_length=20)),
                ('observation', models.BooleanField(default=True)),
                ('evaluation', models.BooleanField(default=True)),
                ('test', models.BooleanField(default=True)),
                ('status_change', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(default='', max_length=100, unique=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('eval_step', models.CharField(default='0', max_length=20)),
                ('record_type', models.CharField(choices=[('O', 'Observation'), ('E', 'Evaluation'), ('T', 'Test'), ('S', 'Status Change')], default='T', max_length=100)),
                ('eval_date', models.DateField(default=datetime.date(2019, 3, 9))),
                ('grade', models.BooleanField(default=True)),
                ('eval_by', models.CharField(default='', max_length=150)),
                ('attachment', models.FileField(upload_to='attachments/%Y/%m/%d/')),
            ],
        ),
    ]
