# Generated by Django 2.1.5 on 2019-03-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
