# Generated by Django 2.1.5 on 2019-03-08 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190309_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='eval_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
