# Generated by Django 2.1.5 on 2019-03-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190309_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='attachment',
            field=models.FileField(upload_to='attachments/%Y/%m/%d/'),
        ),
    ]
