# Generated by Django 2.1.5 on 2019-03-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190311_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingrecord',
            name='EmpID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
